services:
  app:
    build: .
    container_name: laravel_app
    command: sh -c "php artisan serve --host=0.0.0.0 --port=8000"
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - .:/var/www
      - /var/www/node_modules
    depends_on:
      - postgres

  chatbot:
    build: ./chatbot
    container_name: chatbot_api
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: Multipe_agence_location
      DB_USER: postgres
      DB_PASSWORD: 12345
    ports:
      - "8001:8001"
    volumes:
      - ./chatbot:/app

  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: Multipe_agence_location
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - ./projetEnsi.sql:/docker-entrypoint-initdb.d/projetEnsi.sql
      - sail-pgsql:/var/lib/postgresql/data

networks:
  sail:
    driver: bridge

volumes:
  sail-pgsql:
    driver: local